#!/bin/ash
#copyright by monlor
monlorpath=$(uci -q get monlor.tools.path) || exit

miluci="/usr/lib/lua/luci"
monlorweb="$monlorpath/web"
staticdir="/tmp/syslogbackup"
tmpluci="/tmp/mountfiles"

mkdir -p $staticdir &> /dev/null
mkdir -p $tmpluci &> /dev/null
umount -lf $miluci &> /dev/null
rm -rf $staticdir/css
rm -rf $staticdir/img
rm -rf $tmpluci/luci

cp -rf $miluci $tmpluci
mkdir -p $tmpluci/luci/view/web/monlor/
mkdir -p $staticdir/css/
mkdir -p $staticdir/img
ln -sf $monlorweb/lua/api/* $tmpluci/luci/controller/api/
ln -sf $monlorweb/lua/web/* $tmpluci/luci/controller/web/
ln -sf $monlorweb/htm/* $tmpluci/luci/view/web/monlor/
ln -sf $monlorweb/css/* $staticdir/css/
ln -sf $monlorweb/img/* $staticdir/img/

cat $tmpluci/luci/view/web/inc/header.htm | grep monlor > /dev/null 2>&1
if [ $? -ne 0 ]	; then
	sed -i '/高级设置/a\                    <li <%if string.find(REQUEST_URI, "/monlor") then%>class="active"<%end%>><a href="<%=luci.dispatcher.build_url("web","monlor","index")%>"><%:插件中心%></a></li>' $tmpluci/luci/view/web/inc/header.htm
fi	

#model photo
sed -i 's/#admin-mob/#admin-PC/' $tmpluci/luci/view/web/sysauth.htm
sed -i 's/"detail"/"detail" style="display:none;"/' $tmpluci/luci/view/web/sysauth.htm
sed -i 's/"download"/"download" style="display:none;"/' $tmpluci/luci/view/web/sysauth.htm   
sed -i 's/"tip"/"tip" style="display:none;"/' $tmpluci/luci/view/web/sysauth.htm
sed -i 's/<!-- //' $tmpluci/luci/view/web/sysauth.htm
sed -i 's/ -->//' $tmpluci/luci/view/web/sysauth.htm
sed -i 's/minValue="2"//'  $tmpluci/luci/view/web/setting/nat_dmz.htm

mount --bind $tmpluci/luci $miluci

rm -rf /tmp/luci-modulecache
rm -rf /tmp/luci-indexcache
